Added a clone item and clone pacman
cagdasgerede/pacman_workshop pull request #13
Opened 2020-12-09 16:26 UTC by Kerem-Arikan

**I (Kerem Arıkan - 171201076) was assigned to Issue #11.** 

**Features and specifications:**

-The clone Pacman (mentioned temporary character) moves randomly and the item appears at random times in the maze as requested. 

-The item is used by pressing the **"A"** button (can be modified if requested). 

-Only one clone Pacman can appear on the maze at a time. Another clone Pacman **cannot be summoned until the existing clone disappears** after a certain amount of time.

-Clone Pacman is colored blue and is identical to player Pacman in any other way appearance-wise. 

-Clone item is colored as red circle.

-Clone item can be accumulated. Collected number of clone items are shown on the **top right** of the screen.

-Clone Pacman is not affected by the ghosts (can be changed after the code review). It basically clips through them (can also be modified if requested).

**Please let me know if there is a feature or a modification that does not satisfy the requirements. Thank you for your attention**

~Kerem Arıkan
171201076

2020-12-10 04:41 UTC, cagdasgerede commented
Burada yaptığını demo ettiğin bir videonun linkini paylaş.

2020-12-10 04:44 UTC, cagdasgerede requested changes
Needs more work. Add some tests.

2020-12-14 08:14 UTC, Kerem-Arikan commented
Here is my demo video. I have also added the requested tests.

Demo video: https://www.youtube.com/watch?v=qbvUPJdNkUU&feature=youtu.be&ab_channel=KeremAr%C4%B1kan

2020-12-21 01:08 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        if(!this.doesCloneItemExist && decision == 1)
```if(...) {``` parentezi if ile ayni satira tasi.

2020-12-21 01:08 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        }
```} else if(```

2020-12-21 01:09 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        if(this.hasClonePacman())
aç parentezi if ile aynı satıra al

```if(....) {```

2020-12-21 01:09 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        {
ditto

2020-12-21 01:09 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/TileVisitor.java
> +import com.thoughtworks.pacman.core.tiles.CloneItem;
import sirassi yanlis. Duzelt.

2020-12-21 01:13 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/tiles/visitors/DotsLeftVisitor.java
> +import com.thoughtworks.pacman.core.tiles.CloneItem;
import order yanlis

2020-12-21 01:14 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/core/actors/PacmanTest.java
> +    /*
Gereksiz comment

2020-12-21 01:19 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +    private final Pacman pacman;
gereksiz satir sonu boşluk

2020-12-21 01:19 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +import com.thoughtworks.pacman.core.tiles.CloneItem;
import sırasını düzelt

2020-12-21 01:30 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +    public void expireClonePacman()
Kullanılmayan metot?

2020-12-21 06:57 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        java.util.Random random = new java.util.Random();
100. satır ile 135. satırı bir metota alabilir misin?

2020-12-21 07:09 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/tiles/visitors/PacmanTileVisitor.java
> +    {
Tüm yaptığın değişikliklerde parentezi metot ile aynı sıraya taşıyabilir misin?

2020-12-21 07:15 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/tiles/visitors/PacmanTileVisitor.java
> +import com.thoughtworks.pacman.core.tiles.CloneItem;
Import sırası yanlış. Alfabetik olarak Door'dan önce gelmeli.

2020-12-21 07:16 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/tiles/visitors/ScoreTileVisitor.java
> +import com.thoughtworks.pacman.core.tiles.CloneItem;
İmport sırası yanlış.

2020-12-21 07:21 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/presenters/CloneItemPresenterTest.java
> +        assertThat(presenter.getBounds(), equalTo(new Ellipse2D.Double(16*(2*2+1)/2-(12/2), 16*(2*3+1)/2-(12/2), 12, 12)));
Tüm bu sayılar nedir. Bu satırdan anlayamıyorum. Bunları manalı birer değişken olarak tanımlayabilir misin? Ya da aşağıdaki formatta yanlarına açıklama yaz bu formüllerin ve sayıların ne olduğu ile ilgili

```
new Ellipse2D.Double(
  16*(2*2+1)/2-(12/2), /* blah blah */
  16*(2*3+1)/2-(12/2), /* blah blah */
  12, /* blah blah */
  12 /* blah blah */
)
```

2020-12-21 07:24 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        if(this.hasClonePacman())
body yi parentez içerisine al

2020-12-21 07:24 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +            else this.clonePacmanTimePassed++;
body yi parentez içerisine al

2020-12-21 07:24 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +            else this.cloneItemTimePassed++;
else body parentez içerisine al

2020-12-21 07:24 UTC, cagdasgerede requested changes
Kodlarını bıraktığım notlara göre güncelle.

Bir de yorumlara cevap verip Resolve Converation düğmesine basmayı unutma.

Review etmemi istediğinde bana assign etmeyi unutma.

2021-03-22 23:20 UTC, closed without merging