Feature/settings
cagdasgerede/pacman_workshop pull request #16
Opened 2020-12-10 14:39 UTC by Carnagie

2020-12-21 21:37 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/PacmanPresenter.java
> +import java.io.*;
yıldız kullanma

2020-12-21 21:37 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/PacmanPresenter.java
> +        File file=new File("config.txt");    //creates a new file instance
fix indentation

2020-12-21 21:37 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/PacmanPresenter.java
> +        File file=new File("config.txt");    //creates a new file instance
gereksiz comment

2020-12-21 21:37 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/PacmanPresenter.java
> +        FileReader fr=new FileReader(file);   //reads the file
Buradaki commentler gereksiz

2020-12-21 21:38 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/GameScreen.java
> +import java.io.*;
yıldız kullanma

2020-12-21 21:43 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/SettingsScreen.java
> +         System.out.println("error");
sysout görmek istemiyorum

Bu tür exceptionları loga logla.

2020-12-21 21:43 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/SettingsScreen.java
> +}
missing newline

2020-12-21 21:44 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/IntroScreen.java
> +        graphics.drawString("This is gona be awesome",70,20);
Bu nedir?

2020-12-21 21:44 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/IntroScreen.java
> +import java.awt.*;
yıldız kullanma

2020-12-21 21:45 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/PacmanPresenter.java
> +        }catch (IOException ioe){
fix spacing

`}catch (IOException ioe){`

2020-12-21 22:13 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +    public void advance(long timeDeltaInMillis, long timeDeltaInMillis2) {
timeDeltaInMillis2 kötü bir isimlendirme. Daha spesifik bir isim ver.

2020-12-21 22:14 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/GameScreen.java
> +        File file=new File("config.txt");    //creates a new file instance
fix indentation

2020-12-21 22:16 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/GameScreen.java
> +        BufferedReader br=new BufferedReader(fr);  //creates a buffering character input stream
gereksiz commentler var burada

2020-12-21 22:17 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/GameScreen.java
> +            ioe.printStackTrace();
logla

2020-12-21 22:17 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/GameScreen.java
> +
Buradan sonra eklediğim tüm kodu yeni class içerisine al

2020-12-21 22:20 UTC, cagdasgerede requested changes
Video paylaşır mısın? Görsel olarak ne yaptığını görmek istiyorum.

Bu arada neden ActorTest ve GameTest dosyalarını sildin? Eğer bu testler senin değişikliklerinden sonra fail ediyorsa o zaman testleri fix et.

Videonu gördükten sonra daha detaylı review yapacağım. Şimdilik kodda bıraktığım notlara cevap ver ve kodunu notalara göre güncelle. Resolve Converation düğmesine basmayı unutma.

Tekrar review etmemi istediğinde bana assign etmeyi unutma.

2020-12-22 13:37 UTC, Carnagie commented on src/main/java/com/thoughtworks/pacman/ui/presenters/PacmanPresenter.java
> +import java.io.*;
yıldızları düzelttim

2020-12-23 09:36 UTC, Carnagie commented
https://youtu.be/R5DraJXmLoA
Hocam yaptığım değişikliklerin videosu burada.

2021-03-22 23:20 UTC, closed without merging