High score implementation.
cagdasgerede/pacman_workshop pull request #18
Opened 2020-12-12 21:16 UTC by arda-ekinci

High Score implementation.

2020-12-12 21:20 UTC, arda-ekinci commented
https://www.youtube.com/watch?v=cU0KrfHAIxk&ab_channel=ArdaEkinci
Hocam video programından kaynaklı sesim bilgisayar hoparlöründen az gelebilir kulaklıkla dinlerseniz daha net anlaşılıyor.

2020-12-16 08:20 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +import java.awt.*;
* kullanma

2020-12-16 08:23 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +    public boolean scoreControl = false;
public olmasın. Bunun yerine accessor metot yaz.

2020-12-16 08:23 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> -        return new Ghost[] {ghosts.getBlinky(), ghosts.getPinky(), ghosts.getInky(), ghosts.getClyde()};
gereksiz değişiklik

2020-12-16 08:23 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        return new Ghost[]{ghosts.getBlinky(), ghosts.getPinky(), ghosts.getInky(), ghosts.getClyde()};
gereksiz değişiklik

2020-12-16 08:24 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        if (scoreList.size() >= 5) {
5 i constant içerisinde tanımla

2020-12-16 08:24 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +    public void load() {
Bu implementasyonu kendi classına taşı.

2020-12-16 08:24 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        File file = new File(path);
Kullanıcı istediği klasörü arayüzden seçebilmeli.

2020-12-16 08:25 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +                System.out.println("Score file has been created.");
sysout görmek istemiyorum

2020-12-16 08:25 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +            e.printStackTrace();
Bu tür exceptionlar log dosyasına gitmeli

2020-12-16 08:25 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +            e.printStackTrace();
log dosyasına gitmeli

2020-12-16 08:25 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +}
missing newline

2020-12-16 08:26 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScoreBoard.java
> +    public void load() {
Load implementasyonunu kendi classına taşı

2020-12-16 08:27 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScoreBoard.java
> +            e.printStackTrace();
log dosyasına gitmeli

2020-12-16 08:27 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScoreBoard.java
> +            e.printStackTrace();
log dosyasına gitmeli

2020-12-16 08:27 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScoreBoard.java
> +            if (file.createNewFile()) {
true ya da false olması bu koda göre bir şey değiştirmiyor. O zaman if else e gerek yok.

2020-12-16 08:30 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScorePanel.java
> +        String path = System.getProperty("user.dir");
Bu kod ScoreBoard ta da tekrar ediyor. Demekki burada concernler karışmış durumda. Load implementasyonunu kendi klasına taşı ki burdan da o kodu çağırabilir. Böylece iki kere aynı kodu yazarak hem kod base şişmez hem de separation of concerns yaptığın için kodun bakımı/okunması/güncellenmesi/test edilmesi daha kolay olur

2020-12-16 08:30 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScorePanel.java
> +                if (i == 5) break;
5 rakamını constant a koy.

2020-12-16 08:30 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScorePanel.java
> +    public void save() {
save de load gibi ayrı bir klassta yapılmalı

2020-12-16 08:31 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScorePanel.java
> +                //if (scoreList.get(i).score.compareTo(0) != 0)
gerekiz satır

2020-12-16 08:34 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScorePanel.java
> +                    pw.write(scoreList.get(i).name + " " + scoreList.get(i).score.toString() + "\n");
Bu formatlama kısıtlı olmuş. Diyelim ki scoreboarda oyuncunun ulaştığı leveli de yazmak istedik. O zaman nereleri güncellememiz lazım. Bu tür bir değişikliğin kolaylıkla yapılabilir olması lazım. O yüzden bence ScoreEntry diye bir class yap ve oraya name, score vs ekle. ScoreEntry nin toStrıng methodu buradaki formatı belirler. Böylece ScorePanel ile skorun nelerden oluştuğu bilgisini ayırmış olursun

2020-12-16 08:34 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScorePanel.java
> +                if (scoreList.get(j).score.compareTo(scoreList.get(j + 1).score) == -1) {
ScoreEntry classının compareTo metodunu implement edersen buradaki if de daha basitleşir.

2020-12-16 08:36 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/ScorePanel.java
> +    private class Entry {
Bu yukarıda bahsettiğim ScoreEntry classına denk geliyor. Bunu başka bir dosyaya taşı.

scoreboard diye bir klasör yarat. Skor ile ilişkili kodları o klasöre ve pakete taşı.

2020-12-16 08:36 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/core/GameTest.java
> +        assertTrue(game.scoreControl);
Bu neyi test ediyor anlamadım. Daha manalı testler bekliyorum.

2020-12-16 08:38 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/core/GameTest.java
> +    public void GameEntryControl() throws Exception {
metot ismi kodun geneliyle uyumlu değil. `gameEntryControl` olabilir belki. Ama isim biraz manasız geldi. Neyi test ettiği isimden anlaşılmıyor. Test in adı test olursa neyi test ettiği anlaşılmaz. Specific test case neyse onu isimlendir.

2020-12-16 08:38 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/IntroScreenTest.java
> +    /*@Test
Eğer bu teste ihtiyaç yoksa sil.

2020-12-16 08:39 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/ScoreBoardTest.java
> +
gereksiz newline

2020-12-16 08:39 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/ScoreBoardTest.java
> +public class ScoreBoardTest {
Buradaki testler neyi test ediyor? Manasız testler olmuş.

2020-12-16 08:40 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/ScoreBoardTest.java
> +    public void ScoreBoardTextTest() throws Exception {
test isimleri bir şey ifade etmiyor

2020-12-16 08:40 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/ScorePanelTest.java
> +public class ScorePanelTest {
Buradaki testler de manasız. Daha manalı testler bekliyorum.

2020-12-16 08:45 UTC, cagdasgerede requested changes
Kod içerisinde bıraktığım notlara göre kodunu güncelle.

High score listesine girerken bir popup ile kullanıcı adını alıyorsun. Bunu bir popup ile yapmanı istemiyorum. Ana arayüzü güncelle. Aynı şekilde score listesini de ana arayüzde göster. Bir popupta değil.

Testlerin daha manalı olsun. Hangi davranışları eklediğini düşün ve bunların doğru çalışıp çalışmadığını nasıl test edeceksin kafa yor. Usuleten adı test olsun içinde birkaç asser olsun yeter gibi bir yaklaşımla test yazma.

2021-03-22 23:19 UTC, closed without merging