Feature/new sounds
cagdasgerede/pacman_workshop pull request #19
Opened 2020-12-13 11:02 UTC by iremkilinc99

2020-12-15 11:25 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +
gereksiz değişiklik

2020-12-15 11:25 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/BackgroundSoundLoader.java
> +
gereksiz newline

2020-12-15 11:26 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/BackgroundSoundLoader.java
> +    public void playBackground(){
Bu classı bir yerden aldıysan kaynak göster. Ayrıca kodu pacman/thirdparty diye bir klasöre ve package a taşı.

2020-12-15 11:26 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/BackgroundSoundLoader.java
> +        playBackground();
Indentation bozuk

2020-12-15 11:26 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/BackgroundSoundLoader.java
> +private Clip clip ;
indentation bozuk

2020-12-15 11:27 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/BackgroundSoundLoader.java
> +import java.io.File;
package ile import satırı arasında bir newline at.

2020-12-15 11:28 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/BackgroundSoundLoader.java
> +                     System.out.println("sorry");
Error handling doğru değil. Kodda sysout görmek istemiyorum. Loglama yapabilirsin.

2020-12-15 11:28 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/BackgroundSoundLoader.java
> +            } catch (Exception e) {}
Exception handling doğru değil. Loglama yapabilirsin.

2020-12-15 11:28 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/BackgroundSoundLoader.java
> +
fazladan bir newline'ı sil

2020-12-15 11:29 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/FinalSoundLoader.java
> +
gereksiz newline

2020-12-15 11:30 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/FinalSoundLoader.java
> +        File p = new File("pacman_workshop");
Bu class ile üstteki class çok benziyor. Bu iki dosyadaki kodları reuse yapabilecek şekilde yeniden düzenle ve kodları sadeleştir. İki ayrı class aynı kodları bu şekilde tekrar etmesin.

2020-12-15 11:31 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/IntroSoundLoader.java
> +        String a = (p.getAbsolutePath().substring(0, p.getAbsolutePath().indexOf("pacman_workshop")))+ "pacman_workshop/";// to add to relative path
Yine çok benzer tekrar eden kodlar. Üstte yazdığım yorum bura için de geçerli.

2020-12-15 11:31 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/Screen.java
> +    void check();
İsim olarak check den daha tanımlayıcı bir isim bul.

2020-12-15 11:32 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/WinnerSoundLoader.java
> +          File musicPath = new File(a+"src/main/resources/com/thoughtworks/pacman/ui/The Final Countdown .wav");
Hmm, tekrar yine aynı kodları burada görüyorum. Tekrar tekrar aynı classları copy paste etmişsin gibi görünüyor. Tüm bunları ortak bir yerde reuse ederek sadeleştir.

2020-12-15 11:32 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/IntroScreen.java
> +    private  ReentrantLock lock = new ReentrantLock();
private ile ReentrantLock arasında ekstra bir boşluk var.

2020-12-15 11:33 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/IntroScreen.java
> +        }catch (Exception e) {}
```}catch``` => ```} catch```

2020-12-15 11:33 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/IntroScreen.java
> +        if (startGame &&check) {
`&&check` => `&& check`

2020-12-15 11:34 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/LostScreen.java
> +    public void play(){
Bu play ve check metotlarinda da tekrar eden bir durum var. Her classta ayni play ve check metotları bulunuyor. Bunları ortak bir classa taşı ve ya bu ekranları o classtan türet ya da o class ın bir üyesi burada olsun ve ona bu çağrıları delegte et.

2020-12-15 11:35 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/BackgroundSoundLoaderTest.java
> +}
missing newline

2020-12-15 11:35 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/BackgroundSoundLoaderTest.java
> +        assertTrue(throwException());
Testing isminden neyi test ettiğin anlaşılmıyor. Burada niye exception atılmasını bekliyoruz onu da anlamadım.

2020-12-15 11:36 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/BackgroundSoundLoaderTest.java
> +        backgroundSoundLoader = mock(BackgroundSoundLoader.class);
Yine test ismi ile içerideki test kodu ilişkisi anlaşılmıyor.

2020-12-15 11:37 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/FinalSoundLoaderTest.java
> +        finalSoundLoader = new FinalSoundLoader();
Yine benzer test kodları tekrar ediyor. Hem bu testlerin neyi test ettiği anlaşılmıyor hem de gerçekten en önemli test etmek gereken caselerin bunlar olmadığını düşünüyorum.

2020-12-15 11:38 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/FinalSoundLoaderTest.java
> +}
missing new line

2020-12-15 11:39 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/IntroSoundLoaderTest.java
> +        introSoundLoader = new IntroSoundLoader();
Hmm, implementatsyona benzer şekilde testlerde de aynı kodların tekrar tekrar geçtiğini görüyorum. Kod base bu şekilde hem şişiyor hem de kodun anlaşılırlığı azalıyor. Kodun sadeliği ve kodun reuse edilmesi ile ilgili daha özenli olmanı bekliyorum. Buna göre PRdaki tüm kodunu tekrar düzenle.

2020-12-15 11:40 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/GameScreenTest.java
> +
gereksiz değişiklik

2020-12-15 11:40 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/GameScreenTest.java
> +
gereksiz değişiklik

2020-12-15 11:40 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/LostScreenTest.java
>          lostScreen.draw(graphics);
gereksiz değişiklik

2020-12-15 11:43 UTC, cagdasgerede requested changes
Kod içerisinde bıraktığım notlara göre kodunu yeniden güncelle. Özellikle tekrar eden çok fazla kod bloğu var. Bunları yeniden gözden geçirmen gerekiyor. Kozmetik olarak kodda spacing, indentation vb. problemler var. Bunlara da dikkat etmelisin.

İkinci olarak yazdığın test kodlarının hangi test caselerini test ettiği anlaşılmıyor. Önemli test caselerini identify etmede daha özenli olunması gerekiyor. Testlerdeki tekrar eden kod durumunu ve testlerin efektifliğini yeniden gözden geçirmelisin.

2020-12-16 15:57 UTC, iremkilinc99 commented
Onayınıza göre hemen ardından videoyu çekip koymayı planlıyorum.

2020-12-20 09:05 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> -
gereksiz değişiklik

2020-12-20 09:06 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/GameCanvas.java
> +
gereksiz değişiklik

2020-12-20 09:06 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/GameRunner.java
> +
Gereksiz değişiklik

2020-12-20 09:08 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/SoundLoader.java
> +                }else {
fix spacing

```} else {```

2020-12-20 09:08 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/SoundLoader.java
> +                    throw new Exception();
fix indentation

2020-12-20 09:09 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/SoundLoader.java
> +            } catch (Exception e) {}
Bu tür exceptionları log dosyasına logla

2020-12-20 09:09 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/GameScreen.java
> +import java.util.concurrent.locks.Lock;
Kullanılmayan import.

2020-12-20 09:12 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/SoundToScreens.java
> +       if (screenName.equals("IntroSoundLoader"))
Bu if bloğuna neden gerek var? Şöyle çalışmıyor mu?

```
threadSounds = new Thread(soundLoader, screenName);
```

2020-12-20 09:12 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/SoundToScreens.java
> +             stop();
fix indentation

2020-12-20 09:12 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/SoundToScreens.java
> +        }else
fix spacing

```} else```

2020-12-20 09:13 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/SoundToScreens.java
> +        if (screenName.equals("IntroSoundLoader"))
Bu if bloğuna gerek yok.

public void chooseTheSound(){
  play();
}

2020-12-20 09:13 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/SoundToScreens.java
> +}
missing newline

2020-12-20 09:14 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/SoundToScreens.java
> +        } catch (Exception e) {}
Bu tür exceptionları log dosyasına logla

2020-12-20 09:14 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/WinScreen.java
> +
gereksiz değişiklik

2020-12-20 09:15 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/SoundLoaderTest.java
> +        soundLoader = new SoundLoader ("IntroSoundLoader");
fix spacing

2020-12-20 09:15 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/SoundLoaderTest.java
> +    public void playwithNullPath() throws Exception{
playWithNullPath

2020-12-20 09:16 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/SoundLoaderTest.java
> +}
missing newline

2020-12-20 09:16 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/SoundToScreens.java
> +public class SoundToScreens{
fix spacing

```SoundToScreens {```

2020-12-20 09:17 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/IntroScreen.java
> +    public void play (){
fix spacing

```play()```

2020-12-20 09:20 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/SoundLoader.java
> +          if (soundName.equals("IntroSoundLoader"))
Kodda "IntroSoundLoader", "BackgroundSoundLoader", "WinnerSoundLoader", "FinalSoundLoader" Stringleri birkaç yerde geçiyorlar. 

Bu Stringleri SoundConstants.java diye bir dosyada tanımla ve tüm kodda ne zaman bu Stringleri kullanıyorsan, String yerine ilgili constantı kullan.

2020-12-20 09:21 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/SoundLoader.java
> +              musicPath = new File(pacmanPath+"src/main/resources/com/thoughtworks/pacman/ui/pacman_death.wav");
Bu pathlaerde 

src/main/resources/com/thoughtworks/pacman/ui/

tekrar ediyor.

pacmanPath değişkenine ekle.

2020-12-20 09:21 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/SoundLoader.java
> +              musicPath = new File(pacmanPath+"src/main/resources/com/thoughtworks/pacman/ui/The Final Countdown .wav");
Fix spacing

```pacmanPath + "```

2020-12-20 09:26 UTC, cagdasgerede requested changes
Kodlarını bıraktığım notlara göre güncelle.


Jacocoyu çalıştır ve jacoco raporundan SoundLoader.java ve SoundToScreens.java dosyalarının coverage durumunu gösteren ekran görüntüsünü PRda paylaş.

Review etmemi istediğinde bana assign etmeyi unutma.

2020-12-22 13:21 UTC, iremkilinc99 commented
SoundLoader, SoundToScreens ve SoundConstants Coverage ekra görüntüleri ;
![Screenshot from 2020-12-22 16-12-43](https://user-images.githubusercontent.com/59146159/102892597-2bb1d500-4471-11eb-85c8-74e45191e7d6.png)
![Screenshot from 2020-12-22 16-12-29](https://user-images.githubusercontent.com/59146159/102892622-33717980-4471-11eb-9f58-b4e4aff3120f.png)
![Screenshot from 2020-12-22 16-12-48](https://user-images.githubusercontent.com/59146159/102892634-38cec400-4471-11eb-9a1f-a86506b729f1.png)

Demo Linki -->  https://youtu.be/CaQ3Eg-xgFM

2021-03-22 23:19 UTC, closed without merging