Feature/add special item and stop enemies
cagdasgerede/pacman_workshop pull request #21
Opened 2020-12-15 12:35 UTC by bsumluludan

2020-12-15 20:12 UTC, bsumluludan commented
Demo video : https://www.youtube.com/watch?v=qbvUPJdNkUU&feature=youtu.be&ab_channel=KeremAr%C4%B1kan

2020-12-15 20:13 UTC, bsumluludan commented
Demo video : https://www.youtube.com/watch?v=NyvQT5FZtAY&feature=youtu.be

2020-12-19 11:15 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/MazePresenter.java
> +
gereksiz newlinelar

2020-12-19 11:18 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/SpecialItemPresenter.java
> +}
missing line

2020-12-19 11:19 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/core/GameTest.java
> +    /*@Test
Bu testleri neden comment out ettin?

2020-12-19 11:19 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/core/GhostsTest.java
> +    /*@Test
Bu test neden commented out?

2020-12-19 11:23 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/GameScreenTest.java
> +    /*@Test
Bu test neden commented out?

2020-12-19 11:28 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +
Bu bölgeyi yeni bir classa taşı.

2020-12-19 11:28 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +    private long counter=0;
Bu sayaçların isimler, bir şey ifade etmiyor. Daha manalı isimler seç. xxx1, xxx2, xxx3 gibi isimler de kullanmamaya çalış.

2020-12-19 11:29 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +    private long counter=0;
Bu değişlenkleri ve aşağıda eklediğin kodu başka bir classa taşı

2020-12-19 11:29 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +                        TileCoordinate siCoordinate = new TileCoordinate(random_intX,random_intY);
siCoordinate kötü bir seçim. Daha açık bir isim seç.

2020-12-19 11:30 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        if(counter % 200 == 199){
Yukarıda söylediğim gibi bu bölgeleri yeni bir classa taşı.

2020-12-19 11:33 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        }else{
fix spacing
```} else {```

2020-12-19 11:34 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/actors/Ghost.java
> +    public void freeze(){//yeni
```//yeni``` commentlerini sil

2020-12-19 11:34 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/actors/Ghost.java
> +    public void notFreeze(){//yeni
ditto

2020-12-19 11:34 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/actors/Ghost.java
> +    public boolean isFreezed(){//yeni
ditto

2020-12-19 11:34 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/maze/Maze.java
> +
gereksiz newline

2020-12-19 11:35 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/maze/Maze.java
> +
gereksiz newline. Tek newline yeterli (kodun genelinde metotlar arasinda 1 newline var)

2020-12-19 11:35 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/maze/Maze.java
> +
ditto

2020-12-19 11:39 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/tiles/SpecialItem.java
> +public class SpecialItem extends Tile{
```Tile {```

2020-12-19 11:39 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/tiles/SpecialItem.java
> +        return "?";
neden `?`

Daha manali bir toString implement et.

2020-12-19 11:40 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/TileToPresenterFactory.java
> +import com.thoughtworks.pacman.core.tiles.SpecialItem;
SpecialItem iki kere import edilmis

2020-12-19 11:41 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/TileToPresenterFactory.java
> +import com.thoughtworks.pacman.ui.presenters.SpecialItemPresenter;
import sirasi yanlis. Harf sirasina gore WallPresenter dan bir once olmasi lazim

2020-12-19 11:49 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/actors/Ghost.java
> +    private boolean freeze = false; //yeni
```//yeni``` sil

2020-12-19 11:50 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/actors/Ghost.java
> +    public void notFreeze(){//yeni
removeFreeze?

2020-12-19 11:54 UTC, cagdasgerede requested changes
Kod içeriisnde bıraktığım notlara göre kodunu güncelle.

Özellikle Game.java içerisine yazdığın kodları yeni bir classa taşı. Ayrıca SpecialItem çok genel bi isim. Bu item için daha manalı bir isim bul. SpecialItem diye bir abstract class yarat. Bu classtan yeni classını türet. Bu class içerisine yeni fonksiyonları ekle. Her bir SpecialItem kendisi maze'e ne yapacağını bilsin. Maze içerisinde birden fazla ve birden farklı special item olabilir. Dolayısıyla bunları bir arrayde tut. Özetle yalnızca freeze yapan özel bir item değil genel bir özel efektler veren bir hiyerarşi tasarımı yap. Örneğin bir başka special item karakteri görünmez/hasar alamaz yapabilir ve bir süre boyunca karakterin üzerinden geçseler bile karakter kaybetmez. Şu anki kodda bunun için bir çok tekrar eden kod yazmak gerekir ve sistematik olarka böyle bir special item ı eklemek çok kolay olmaz. Çok sayıda special item olabileceği olasılığı üzerinden tasarımını yeniden gözden geçir.

Yeni eklediğin kodlar için manalı unit testler yazmayı unutma. Mock edilmesi gereken yerler varsa mockito kullan.

2021-03-22 23:18 UTC, closed without merging