Feature/co-op-playing
cagdasgerede/pacman_workshop pull request #22
Opened 2020-12-15 16:10 UTC by berkayert7

-Multiplayer is activated when the "m" key is pressed in the intro page. 
-The player on the right moves with the arrow keys, the player on the left with the w, a, s, d keys.

![Game SS](https://user-images.githubusercontent.com/67527179/102240281-baba6c80-3f08-11eb-8c2a-0d5fe0894226.png)

2020-12-19 07:58 UTC, cagdasgerede commented
Bu PR'ı bana assign etmen gerekiyor. Reviewer olarak eklemen yeterli değil. Aksi halde benim review listeme düşmüyor. Bu durumu Discord üzerinden sizlere duyurmuştum. Bundan sonra da güncellemelerini yaptıktan sonra PRı bana assign etmeyi unutma.

2020-12-19 08:03 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/MazePresenter.java
> +        graphics.drawString(String.format("%2d", maze.getScore()), Tile.SIZE * 5+xOffset, Tile.SIZE * 2);
missing space

```5 + xOffset```

2020-12-19 08:04 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/WallPresenter.java
> +        this.wall = new Wall(new TileCoordinate(coordinate.getX()+xOffset/ Tile.SIZE, coordinate.getY()), type);
fix spacing

```getX() + xOffset```

2020-12-19 08:04 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/MultiplayerEndScreen.java
> +import java.awt.*;
* kullan

2020-12-19 08:05 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/MultiplayerEndScreen.java
> +    static final Image WIN_SCREEN_IMAGE = ImageLoader.loadImage(Screen.class, "winScreen.jpg");
private static final Image

2020-12-19 08:06 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/MultiplayerEndScreen.java
> +    static final Image LOST_SCREEN_IMAGE = ImageLoader.loadImage(Screen.class, "gameOver.png");
private static final Image

2020-12-19 08:11 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/MultiplayerGameScreen.java
> +        this(game1, game2, new GamePresenter(game1, game2.getDimension().width+ Tile.SIZE*2), new GamePresenter(game2));
```getDimension().width + ```

2020-12-19 08:12 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/screens/MultiplayerGameScreen.java
> +}
missing newline

2020-12-19 08:14 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/PacmanPresenter.java
> +import java.awt.*;
```awt.*``` kullanma. Class isimlerini acikca listele

2020-12-19 08:22 UTC, cagdasgerede requested changes
Kodda biraktigim notlara gore kodunu guncelle.

Yeni ekledigin ozelleklerle ilgili testler ekle. Eger test yazmakta zorlanirsan kodundaki ana fonksiyonlari metotlara al ve bu metotlar icin test yaz.

Bir de su ana kadar yaptiklarini anlattigin vide videonun linkini PR threadinde paylas.

Tekrar review etmem icin hazir oldugunda PRi tekrar bana assign et.

2020-12-24 20:04 UTC, berkayert7 commented
https://youtu.be/2UjIysIso5Q

2021-03-22 23:18 UTC, closed without merging