added an freezing item bomb for ghosts
cagdasgerede/pacman_workshop pull request #24
Opened 2020-12-15 20:59 UTC by boraserel

added an freezing item bomb for ghosts

2020-12-15 21:39 UTC, boraserel commented
![Screenshot_7](https://user-images.githubusercontent.com/69976753/102275788-f9671b80-3f36-11eb-866b-169899025c52.png)

-2 new items are added
	*FreezingItem which can be collected by our pacman(shown as red rect.)
	*FreezingItemBomb which can be dropped(used) by our pacman and freezes ghost which touches it.(shown as blue rect.)
	
-modifiable components
	*FreezingItemBomb key assigned to SPACE
	*GhostFreezeTime and SpeedAfterFreeze
		-can be used for implementing ghost health?.
	*FreezingItem's maximum alive Time
        *FreezingItem's spawn frequency

2020-12-19 14:09 UTC, cagdasgerede commented on .project
> +	<comment></comment>
Bu dosya senin development environmentin ile ilgili bir dosya. Bu dosyayi .gitignore'a ekle ve projeden sil.

2020-12-19 14:10 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Actor.java
> +    private int SPEED = 100;
Artik constant olmadigi icin 

```SPEED``` -> ```speed```

2020-12-19 14:12 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Actor.java
> +        this.SPEED=SPEED;
fix spacing

```this.speed = speed```

2020-12-19 14:12 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Actor.java
> +        return SPEED;
return speed;

2020-12-19 14:13 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +import com.thoughtworks.pacman.core.tiles.Dot;
Bu importlar
```import com.thoughtworks.pacman.core.tiles.visitors.PacmanTileVisitor;``` önce olmalı

2020-12-19 14:14 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +    private final int maxAliveTime=200;
Fix spacing:

```maxAliveTime = 200```
```ghostFreezeTime=100;```
```defaultGhostSpeed=100;```

2020-12-19 14:16 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +    private final int ghostFreezeTime=100;
Bu dosyada yaptigin degisiklikleri olabildigince baska bir class icerisine encapsulate etmeye calis.

2020-12-19 14:16 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        if(activeBombCount>0){
Bu kismi yenir bir class icerisine al. Classa oyun ile ilgili gerekli datalari pass edersin. O da gerekli guncellemeleri yapar.

Bu sekilde bu tur baska itemler ekledigimizde bu klass sismez.

2020-12-19 14:17 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +    private int BlinkyFreezingTimePassed = 0;
Bu degiskenlerin isimleri kodun geneli ile uyulu degil.

Degiskenler kucuk harfle baslamalilar.

2020-12-19 14:18 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +            for(int i=0;i<=3;i++){
3 yerine ghostsArray.length kullan

ayrica buradaki horizontal space e dikkat et.

```for(int i = 0; i <= 3; i++)```

2020-12-19 14:18 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +                    switch(i){
```siwtch(i) {```

2020-12-19 14:20 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +
gereksiz newline

2020-12-19 14:20 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        int spawnDecision = r.nextInt(15);
15 i ismi manali bir constant olarak tanimla.

2020-12-19 14:21 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +                freezingItemTimePassed=0;
fix horizontal spacing

```freezingItemTimePassed = 0;```

2020-12-19 14:21 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/Game.java
> +        if(this.maze.isFreezingItemAlive()==false && spawnDecision==1){
```Alive() == false && spawnDecision == 1```

2020-12-19 14:21 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/TileVisitor.java
> +	T visit(FreezingItemBomb freezingItemBomb);
fix indentation

2020-12-19 14:23 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/TileVisitor.java
> +	T visit(FreezingItemBomb freezingItemBomb);
FreezingItem yerine CollectableItem gibi bir abstract class yarat ve bir tane visit metodu yaz. Her ikisi de FreezingItem'dan tureyen subclass lar olabilir. Bu sekilde ortak olan kodlari da parent classaa tasiyabilirsin.

2020-12-19 14:23 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/maze/Maze.java
> +
extra newlinei sil

2020-12-19 14:24 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/maze/Maze.java
> +        if(freezingItemCount<=0)
```freezingItemCoun <= 0```

2020-12-19 14:24 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/maze/Maze.java
> +        oldTile=this.tiles.get(freezingItemCoordinate);
fix spacing

2020-12-19 14:31 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/tiles/visitors/PacmanTileVisitor.java
> +import com.thoughtworks.pacman.core.tiles.FreezingItem;
import order alfabetik olacak. Sirayi duzelt.

2020-12-19 14:32 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/FreezingItemBombPresenter.java
> +}
missing newline

2020-12-19 14:32 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/FreezingItemPresenter.java
> +}
missing newline

2020-12-19 14:32 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/ui/presenters/FreezingItemPresenter.java
> +    private static final int SIDE = 12;
Bu classta ve diger FreezingItem classinda kodlar tekrar ediyor. Ortak bir parenta ortak kodlari tasi.

2020-12-19 14:34 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/GameScreenTest.java
> +        Thread.sleep(10); // Some time for pacman to move
1ms ile 10ms arasinda ne fark var? Niye 10 yapman gerekiyor?

2020-12-19 14:34 UTC, cagdasgerede commented on src/test/java/com/thoughtworks/pacman/ui/screens/GameScreenTest.java
> +
gereksiz newline

2020-12-19 14:36 UTC, cagdasgerede commented on src/main/java/com/thoughtworks/pacman/core/maze/Maze.java
> +    public FreezingItem getAliveItem() {
Bu classa yeni ekledigin kodlar sanki burada olmamasi lazim. Su anda Maze bu kodlarla buyuyor. Bu tarz baska itemler eklesek daha da sisecek. Bu kismi daha farkli tasarlabilir misin? Maze icerisine eklenen kod minimum olsun. Olabildigince kodu ozel dogrudan bu yeni ozellikle ilgili bir classa tasimaya calis. Kucuk bir integration ile de o classin metotlarini cagirirsin.

Ayni durum Game.java icin de gecerli.

2020-12-19 14:38 UTC, cagdasgerede requested changes
Kod icerisine biraktigim notlara gore kodunu guncelle.

Bir de su ana kadar yaptiklarini anlatan videonun linkini burada paylas.

Yeniden reviewe hazir oldugunda PRi bana assign etmeyi unutma.

2020-12-23 15:02 UTC, boraserel commented on src/test/java/com/thoughtworks/pacman/ui/screens/GameScreenTest.java
> +        Thread.sleep(10); // Some time for pacman to move
Hocam 1 ms'de oyun ici islemlerin hepsi (index kontrolu vs.) saglanmadi ve test gecmedi. Onun icin uzattim.

2020-12-23 19:21 UTC, boraserel commented
video linki : [https://youtu.be/l4CI4GCV3jw](url)

Hocam belirttiginiz degisiklikleri gerceklestirdim. Reviewe hazir.

2021-03-22 23:18 UTC, closed without merging